[build]
  command = "CI=false NODE_ENV=production npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  NODE_ENV = "production" 